# Generated by Django 5.0.6 on 2026-05-26 04:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esg_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('issuing_body', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'frameworks',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('guidance', models.TextField(blank=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='frameworks.framework')),
                ('linked_metrics', models.ManyToManyField(blank=True, related_name='framework_requirements', to='esg_data.metricdefinition')),
            ],
            options={
                'db_table': 'framework_requirements',
                'ordering': ['framework', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationFramework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adopted_at', models.DateField()),
                ('is_primary', models.BooleanField(default=False)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frameworks.framework')),
            ],
            options={
                'db_table': 'organization_frameworks',
            },
        ),
    ]
