# Generated by Django 5.0.6 on 2026-05-26 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frameworks', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationframework',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_frameworks', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='frameworkrequirement',
            unique_together={('framework', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationframework',
            unique_together={('organization', 'framework')},
        ),
    ]
