# Generated by Django 5.0.6 on 2026-05-26 04:35

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESGDataPoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('collection_method', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated'), ('estimated', 'Estimated'), ('calculated', 'Calculated')], default='manual', max_length=30)),
                ('confidence_level', models.PositiveSmallIntegerField(default=100, help_text='Data confidence 0-100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list, help_text='List of S3 keys for supporting documents')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'esg_data_points',
            },
        ),
        migrations.CreateModel(
            name='ESGTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('absolute', 'Absolute Reduction'), ('intensity', 'Intensity Reduction'), ('percentage', 'Percentage Improvement')], max_length=20)),
                ('baseline_year', models.PositiveSmallIntegerField()),
                ('baseline_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('target_year', models.PositiveSmallIntegerField()),
                ('target_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('is_science_based', models.BooleanField(default=False)),
                ('framework_alignment', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'esg_targets',
                'ordering': ['target_year', 'metric__category'],
            },
        ),
        migrations.CreateModel(
            name='MaterialityAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1)),
                ('financial_materiality_score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('impact_materiality_score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_material', models.BooleanField(default=False)),
                ('rationale', models.TextField(blank=True)),
                ('stakeholder_groups', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'esg_materiality_assessments',
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], db_index=True, max_length=1)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('unit', models.CharField(choices=[('tCO2e', 'Tonnes CO2e'), ('MWh', 'Megawatt-hours'), ('m3', 'Cubic Meters'), ('%', 'Percentage'), ('#', 'Number'), ('USD', 'USD'), ('ratio', 'Ratio'), ('hours', 'Hours'), ('tonnes', 'Tonnes')], max_length=20)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('boolean', 'Boolean'), ('percentage', 'Percentage')], default='numeric', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('calculation_guidance', models.TextField(blank=True)),
                ('framework_mappings', models.JSONField(default=dict, help_text='Maps to GRI, SASB, TCFD, etc.')),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'esg_metric_definitions',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='annual', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'esg_reporting_periods',
                'ordering': ['-start_date'],
            },
        ),
    ]
