# Generated by Django 5.0.6 on 2026-05-26 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esg_data', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esgdatapoint',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_data_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_data_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esgtarget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esgtarget',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_targets', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiality_assessments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='esgtarget',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='esg_data.metricdefinition'),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_points', to='esg_data.metricdefinition'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_data.reportingperiod'),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='esg_data.reportingperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='reportingperiod',
            unique_together={('organization', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='materialityassessment',
            unique_together={('organization', 'reporting_period', 'topic')},
        ),
        migrations.AddIndex(
            model_name='esgdatapoint',
            index=models.Index(fields=['organization', 'status'], name='esg_data_po_organiz_c932bf_idx'),
        ),
        migrations.AddIndex(
            model_name='esgdatapoint',
            index=models.Index(fields=['metric', 'reporting_period'], name='esg_data_po_metric__db393a_idx'),
        ),
        migrations.AddIndex(
            model_name='esgdatapoint',
            index=models.Index(fields=['status', 'submitted_at'], name='esg_data_po_status_359052_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='esgdatapoint',
            unique_together={('organization', 'metric', 'reporting_period', 'facility')},
        ),
    ]
