# Generated by Django 5.0.6 on 2026-05-28 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct Emissions'), ('scope_2', 'Scope 2 — Indirect (Electricity)'), ('scope_3', 'Scope 3 — Value Chain')], max_length=10)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ghg_protocol_category', models.CharField(blank=True, max_length=100)),
                ('source_types', models.JSONField(default=list, help_text='Which source types map to this category')),
            ],
            options={
                'db_table': 'emission_categories',
                'ordering': ['scope', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct Emissions'), ('scope_2', 'Scope 2 — Indirect (Electricity)'), ('scope_3', 'Scope 3 — Value Chain')], db_index=True, max_length=10)),
                ('source_type', models.CharField(db_index=True, max_length=20)),
                ('activity_value', models.DecimalField(decimal_places=6, help_text='Normalized activity quantity (liters, kWh, km, nights)', max_digits=20)),
                ('activity_unit', models.CharField(help_text='Normalized unit: L, kWh, km, nights', max_length=20)),
                ('activity_date', models.DateField(db_index=True)),
                ('activity_period_start', models.DateField(blank=True, null=True)),
                ('activity_period_end', models.DateField(blank=True, null=True)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, help_text='kg CO2e per unit of activity', max_digits=20, null=True)),
                ('emission_factor_source', models.CharField(blank=True, help_text='e.g. IPCC 2021, DEFRA 2023, EPA 2023', max_length=100)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated CO2e in kilograms', max_digits=20, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('document_reference', models.CharField(blank=True, max_length=200)),
                ('original_unit', models.CharField(blank=True, max_length=20)),
                ('original_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Audit Locked'), ('flagged', 'Flagged — Needs Review')], db_index=True, default='pending', max_length=20)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('suspicious_reasons', models.JSONField(default=list)),
                ('validation_errors', models.JSONField(default=list)),
                ('transformation_log', models.JSONField(default=list, help_text='Ordered list of transformations applied: [{step, from, to, note}]')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.uploadbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_records', to='organizations.department')),
                ('emission_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='normalization.emissioncategory')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_records', to='organizations.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'normalized_records',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review'), ('escalated', 'Escalated')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='normalization.normalizedrecord')),
            ],
            options={
                'db_table': 'approval_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['organization', 'scope', 'status'], name='normalized__organiz_7a0d11_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['organization', 'source_type', 'activity_date'], name='normalized__organiz_249d55_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['batch', 'status'], name='normalized__batch_i_9cebab_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['is_suspicious', 'status'], name='normalized__is_susp_1f5b63_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['normalized_record', 'created_at'], name='approval_wo_normali_44fced_idx'),
        ),
    ]
