# Generated by Django 5.0.6 on 2026-05-26 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('integration_type', models.CharField(choices=[('rest_api', 'REST API'), ('sftp', 'SFTP'), ('database', 'Database'), ('webhook', 'Webhook'), ('manual_upload', 'Manual Upload')], max_length=20)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Encrypted connection config')),
                ('field_mappings', models.JSONField(default=dict, help_text='Maps source fields to ESG metric codes')),
                ('sync_frequency', models.CharField(default='daily', max_length=50)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_records', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'data_integrations',
                'ordering': ['name'],
            },
        ),
    ]
