# Generated by Django 5.0.6 on 2026-05-26 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('gri', 'GRI Standards'), ('tcfd', 'TCFD'), ('sasb', 'SASB'), ('cdp', 'CDP'), ('csrd', 'CSRD'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('generation_config', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
