# Generated by Django 5.0.6 on 2026-05-26 04:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(choices=[('energy', 'Energy'), ('manufacturing', 'Manufacturing'), ('finance', 'Finance'), ('technology', 'Technology'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('real_estate', 'Real Estate'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('other', 'Other')], default='other', max_length=30)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('description', models.TextField(blank=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fiscal_year_end', models.CharField(default='12-31', help_text='MM-DD', max_length=5)),
                ('reporting_currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('settings', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('esg_manager', 'ESG Manager'), ('analyst', 'Analyst'), ('viewer', 'Viewer'), ('auditor', 'Auditor')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organization_memberships',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('office', 'Office'), ('manufacturing', 'Manufacturing'), ('warehouse', 'Warehouse'), ('data_center', 'Data Center'), ('retail', 'Retail'), ('other', 'Other')], default='office', max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='organizations.organization')),
            ],
            options={
                'db_table': 'facilities',
                'ordering': ['organization', 'name'],
            },
        ),
    ]
